Repository Hanziness/FocusTide, pull requests merged in 2022-07, with the labels that each got.

#243 i18n: add french translation
  i18n/fr.json
  nuxt.config.js
Labels: translations 🌍

#242 fix: onboarding buttons uses translated string
  components/tutorial/tutorialOnboarding.vue
Labels: bug 🐛

#244 refactor(ui): Revamp basic UI components
  assets/css/disable_tap_highlight.css
  components/base/button.vue
  components/base/inputText.vue
  components/base/toggle.vue
  components/settings/baseSettingsItem.vue
  components/settings/exportButton.vue
  components/settings/importButton.vue
  components/settings/items/settingsCheck.vue
  components/settings/settingsPanel.vue
  components/todoList/addTask.vue
  components/todoList/item.vue
  components/todoList/main.vue
  components/tutorial/tutorialOnboarding.vue
  pages/timer.vue
  tailwind.config.js
Labels: refactor

#249 feat: Add app event recording
  components/notifications/notificationController.vue
  components/ticker.vue
  components/timer/controls/contolsBasic.vue
  pages/timer.vue
  stores/events.js
  stores/settings.js
Labels: enhancement
